import { test, expect } from '@playwright/test';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import * as pty from 'node-pty';
import { createApp } from '../src/server.js';
import { ConfigStore } from '../src/config.js';
import { Sessions } from '../src/sessions.js';
import { ClaudeAdapter } from '../src/agents/claude.js';
import { AgentRegistry } from '../src/agents/registry.js';

test('agent tabs persist across browsers and service restarts without eager process creation', async ({ page, browser }, testInfo) => {
  const directory = await mkdtemp(join(tmpdir(), 'mam-browser-'));
  let store = await new ConfigStore(directory).load();
  let spawns = 0;
  const commands: string[] = [];
  const initScript = 'export MAM_TEST_ENV="hello world"\nexport PATH="$HOME/.local/bin:$PATH"';
  const historyId = randomUUID(), missingId = randomUUID();
  const records = new Map([
    [historyId, { id: historyId, cwd: '/srv/existing-project', title: '接入之前已有的对话', modified: 1789200000 }],
    [missingId, { id: missingId, cwd: '/srv/missing', title: '即将删除的对话', modified: 1789200001 }],
  ]);
  const createSessions = () => new Sessions((_agent, command, cols, rows) => {
    spawns++; commands.push(command);
    const id = /--session-id '([^']+)'/.exec(command)?.[1];
    if (id) records.set(id, { id, cwd: '/srv/project', title: '修复终端刷新问题', modified: 1789200002 });
    return pty.spawn('/bin/bash', ['--noprofile', '--norc', '-c', 'printf "CLAUDE TERMINAL TEST\\n"; while IFS= read -r line; do if [ "$line" = exit ]; then break; fi; printf "REPLY:%s\\n" "$line"; done'], { cols, rows, name: 'xterm-256color' });
  });
  const createClaude = () => new ClaudeAdapter(async (agent, command) => {
    if (agent.target === 'unreachable') throw new Error('SSH connection refused (test)');
    if (agent.initScript) expect(command).toContain('eval ');
    if (command.includes('--help')) return '--session-id --resume\nPython 3.12';
    const options = JSON.parse(command.slice(command.indexOf("python3 - '") + "python3 - '".length, command.lastIndexOf("'")));
    const all = [...records.values()];
    const matching = options.sessionId ? all.filter(item => item.id === options.sessionId) : options.sessionIds ? all.filter(item => options.sessionIds.includes(item.id)) : all;
    return '__AGENT_HUB_JSON__' + JSON.stringify({ items: matching.slice(options.offset, options.offset + options.limit), total: matching.length, warnings: [] });
  });
  let sessions = createSessions();
  let app = await createApp({ store, sessions, registry: new AgentRegistry([createClaude()]), dev: true });
  let origin = await app.listen(0);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const openPicker = async () => { await page.getByRole('button', { name: '添加对话', exact: true }).click(); await expect(page.getByRole('dialog', { name: '打开对话' })).toBeVisible(); };
  const chooseAgent = async (name: string) => { await page.getByRole('combobox', { name: '选择 Agent' }).click(); await page.getByRole('option', { name, exact: true }).click(); };
  const activeTab = () => page.getByRole('tab', { selected: true });
  try {
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.locator('.sidebar, .statusbar, .list-footer')).toHaveCount(0);
    await expect(page.getByRole('img', { name: 'Agent Hub' })).toBeVisible();
    await expect(page.locator('.brand-dark')).toBeVisible();
    await expect(page.getByRole('combobox', { name: '颜色主题' })).toHaveValue('modernDark');
    await page.getByRole('combobox', { name: '颜色主题' }).selectOption('modernLight');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'modernLight');
    await expect(page.locator('.brand-light')).toBeVisible();
    await page.reload();
    await expect(page.getByRole('combobox', { name: '颜色主题' })).toHaveValue('modernLight');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'modernLight');
    await page.screenshot({ path: testInfo.outputPath('theme-light.png'), fullPage: true });
    await page.getByRole('combobox', { name: '颜色主题' }).selectOption('modernDark');
    await page.getByRole('button', { name: '注册第一个 Agent' }).click();
    await page.getByLabel('名称', { exact: true }).fill('Dev Claude');
    await page.getByLabel('SSH 目标', { exact: true }).fill('dev-host');
    await page.getByLabel('默认工作目录', { exact: true }).fill('/srv/project');
    await page.getByText('高级配置', { exact: true }).click();
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill(initScript);
    await page.getByRole('button', { name: '测试连接', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('检查通过');
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.locator('.agent-controls .claude-icon')).toBeVisible();
    await expect(page.getByRole('region', { name: '打开对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '新建对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '打开历史对话' })).toBeVisible();
    await expect(page.getByRole('tab')).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('empty.png'), fullPage: true });
    await expect(page.locator('.tab-actions button')).toHaveCount(1);
    await expect(page.getByRole('button', { name: '添加对话' })).toHaveText('+');
    await openPicker();
    await expect(page.getByRole('dialog', { name: '打开对话' }).getByRole('heading', { name: '新建对话' })).toBeVisible();
    await expect(page.getByRole('dialog', { name: '打开对话' }).getByRole('heading', { name: '打开历史对话' })).toBeVisible();
    await expect(page.getByRole('button', { name: '原生历史选择器' })).toHaveCount(0);
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: '关闭' }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button', { name: '启动 Claude Code', exact: true }).click();
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    await page.getByRole('combobox', { name: '颜色主题' }).selectOption('solarizedDark');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'solarizedDark');
    await expect(page.locator('.xterm-viewport')).toHaveCSS('background-color', 'rgb(0, 43, 54)');
    await page.getByRole('combobox', { name: '颜色主题' }).selectOption('modernDark');
    await expect(activeTab()).toContainText('修复终端刷新问题');
    const firstSession = sessions.list()[0];
    const agentId = store.get().agents[0].id;
    await page.locator('.xterm-helper-textarea').fill('browser-input');
    await page.locator('.xterm-helper-textarea').press('Enter');
    await openPicker();
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    expect(commands.at(-1)).toContain(`--resume '${historyId}'`);
    await expect(page.getByRole('tab')).toHaveCount(2);
    await openPicker();
    await expect(page.getByRole('heading', { name: '新建对话', exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('add-conversation.png'), fullPage: true });
    await page.getByLabel('搜索对话').fill('existing-project');
    await expect(page.locator('.conversation')).toHaveCount(1);
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(page.getByRole('tab')).toHaveCount(2);
    expect(spawns).toBe(2);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).press('ArrowRight');
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await page.reload();
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    expect(spawns).toBe(2);
    await page.screenshot({ path: testInfo.outputPath('tabs.png'), fullPage: true });

    await page.getByRole('button', { name: '管理 Agents' }).click();
    await expect(page.locator('.managed-agent .claude-icon').first()).toBeVisible();
    await page.getByRole('button', { name: '注册 Agent', exact: true }).click();
    await page.getByLabel('名称', { exact: true }).fill('Second Claude');
    await page.getByLabel('SSH 目标', { exact: true }).fill('dev-host');
    await page.getByText('高级配置', { exact: true }).click();
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill(initScript);
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.getByRole('combobox', { name: '选择 Agent' })).toContainText('Second Claude - dev-host');
    await page.getByRole('combobox', { name: '选择 Agent' }).click();
    await expect(page.getByRole('group', { name: 'SSH · dev-host' })).toBeVisible();
    await expect(page.getByRole('option', { name: 'Dev Claude' }).locator('.claude-icon')).toBeVisible();
    await expect(page.getByRole('option', { name: 'Second Claude' }).locator('.claude-icon')).toBeVisible();
    await page.getByRole('combobox', { name: '选择 Agent' }).press('Escape');
    await expect(page.getByRole('listbox', { name: 'Agents' })).toHaveCount(0);
    await expect(page.getByRole('tab')).toHaveCount(0);
    await openPicker();
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(activeTab()).toContainText('接入之前已有的对话');
    expect(spawns).toBe(2);
    await chooseAgent('Dev Claude');
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(activeTab()).toContainText('接入之前已有的对话');
    const deletes: string[] = [];
    page.on('request', request => { if (request.method() === 'DELETE' && new URL(request.url()).pathname.startsWith('/api/sessions/')) deletes.push(request.url()); });
    await page.getByRole('button', { name: '关闭 修复终端刷新问题' }).click();
    await expect(page.getByRole('tab')).toHaveCount(1);
    expect(sessions.get(firstSession.id)?.info.status).toBe('running');
    await page.reload();
    await expect(page.getByRole('tab')).toHaveCount(1);
    await openPicker();
    await page.getByRole('button', { name: /修复终端刷新问题.*活跃/ }).click();
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    expect(spawns).toBe(2);
    expect(store.get().workspace.agents[agentId].tabs.map(tab => tab.agentSessionId)).toEqual([historyId, firstSession.agentSessionId]);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await expect(page.locator('.xterm-screen')).toContainText('REPLY:browser-input');
    expect(deletes).toEqual([]);

    const savedWorkspace = store.get().workspace;
    await page.close();
    const freshContext = await browser.newContext();
    page = await freshContext.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    expect(store.get().workspace).toEqual(savedWorkspace);
    expect(spawns).toBe(2);
    await page.setViewportSize({ width: 390, height: 720 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(page.getByRole('button', { name: '添加对话', exact: true })).toBeInViewport();
    await page.screenshot({ path: testInfo.outputPath('narrow.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 980 });
    await openPicker();
    await page.getByRole('button', { name: /即将删除的对话/ }).click();
    await expect(activeTab()).toContainText('即将删除的对话');
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await page.close();
    await app.close();
    records.delete(missingId);
    store = await new ConfigStore(directory).load();
    sessions = createSessions();
    app = await createApp({ store, sessions, registry: new AgentRegistry([createClaude()]), dev: true });
    origin = await app.listen(0);
    const beforeResume = spawns;
    page = await freshContext.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.getByRole('tab')).toHaveCount(3);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    expect(sessions.list()).toHaveLength(1);
    expect(spawns).toBe(beforeResume + 1);
    expect(commands.at(-1)).toContain(`--resume '${firstSession.agentSessionId}'`);
    await page.screenshot({ path: testInfo.outputPath('restore.png'), fullPage: true });
    await page.getByRole('tab').last().click();
    await expect(page.getByRole('alert')).toContainText('Agent 历史已删除');
    expect(spawns).toBe(beforeResume + 1);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(page.locator('.terminal-status')).toContainText('已连接');
    expect(spawns).toBe(beforeResume + 1);
    await expect(page.getByRole('tab')).toHaveCount(3);
    await page.locator('.xterm-helper-textarea').fill('exit');
    await page.locator('.xterm-helper-textarea').press('Enter');
    await expect(page.locator('.terminal-status')).toContainText('进程已退出');
    await expect(activeTab()).toContainText('已退出');
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    for (let count = 3; count > 0; count--) { await page.locator('.tab-close').last().click(); await expect(page.getByRole('tab')).toHaveCount(count - 1); }
    await expect(page.getByRole('region', { name: '打开对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '新建对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '打开历史对话' })).toBeVisible();
    await page.reload();
    await expect(page.getByRole('tab')).toHaveCount(0);
    await chooseAgent('Second Claude');
    await expect(page.getByRole('tab')).toHaveCount(1);
    await page.getByRole('button', { name: '管理 Agents' }).click();
    await page.getByRole('button', { name: '编辑 Second Claude' }).click();
    await page.getByText('高级配置', { exact: true }).click();
    await expect(page.getByLabel('初始化脚本（Bash）', { exact: true })).toHaveValue(initScript);
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill('export MAM_TEST_ENV=changed');
    await page.screenshot({ path: testInfo.outputPath('init-script.png'), fullPage: true });
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.getByText('Agent 环境已更改，无法在当前环境恢复此 tab。')).toBeVisible();
    await page.getByRole('button', { name: '管理 Agents' }).click();
    await page.getByRole('button', { name: '编辑 Second Claude' }).click();
    await page.getByLabel('SSH 目标', { exact: true }).fill('unreachable');
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.getByText('Agent 环境已更改，无法在当前环境恢复此 tab。')).toBeVisible();
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    await openPicker();
    await expect(page.getByRole('dialog').getByRole('alert')).toContainText('connection refused');
    await page.getByLabel('搜索对话').fill('no results');
    await expect(page.getByText('没有匹配的对话')).toBeVisible();
    const saved = await readFile(join(directory, 'config.json'), 'utf8');
    expect(saved).not.toContain('browser-input');
    expect(saved).not.toContain('修复终端刷新问题');
    expect(saved).not.toContain('接入之前已有的对话');
    expect(saved).toContain(historyId);
    expect(errors.filter(message => message !== 'WebSocket closed without opened.')).toEqual([]);
    await freshContext.close();
  } finally { await app.close(); await rm(directory, { recursive: true, force: true }); }
});
