import { test, expect } from '@playwright/test';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import * as pty from 'node-pty';
import { createApp } from '../src/server.js';
import { ConfigStore } from '../src/config.js';
import { AuxiliaryShells, Sessions } from '../src/sessions.js';
import { ClaudeAdapter } from '../src/agents/claude.js';
import { AgentRegistry } from '../src/agents/registry.js';

test('agent tabs persist across browsers and service restarts without eager process creation', async ({ page, browser }, testInfo) => {
  const directory = await mkdtemp(join(tmpdir(), 'mam-browser-'));
  let store = await new ConfigStore(directory).load();
  let spawns = 0;
  const commands: string[] = [];
  const initScript = 'export MAM_TEST_ENV="hello world"\nexport PATH="$HOME/.local/bin:$PATH"';
  const historyId = randomUUID(), missingId = randomUUID();
  const records = new Map([
    [historyId, { id: historyId, cwd: '/srv/existing-project', title: '接入之前已有的对话', modified: 1789200000 }],
    [missingId, { id: missingId, cwd: '/srv/missing', title: '即将删除的对话', modified: 1789200001 }],
  ]);
  const createSessions = () => new Sessions((_agent, command, cols, rows) => {
    spawns++; commands.push(command);
    const id = /--session-id '([^']+)'/.exec(command)?.[1];
    if (id) records.set(id, { id, cwd: '/srv/project', title: '修复终端刷新问题', modified: 1789200002 });
    return pty.spawn('/bin/bash', ['--noprofile', '--norc', '-c', 'printf "CLAUDE TERMINAL TEST\\n"; while IFS= read -r line; do if [ "$line" = exit ]; then break; fi; if [ "$line" = scrollback ]; then i=1; while [ "$i" -le 200 ]; do printf "SCROLLBACK:%03d\\n" "$i"; i=$((i + 1)); done; else printf "REPLY:%s\\n" "$line"; fi; done'], { cols, rows, name: 'xterm-256color' });
  });
  let shellSpawns = 0;
  const createAuxiliaryShells = () => new AuxiliaryShells((_agent, _command, cols, rows) => {
    shellSpawns++;
    return pty.spawn('/bin/bash', ['--noprofile', '--norc', '-c', 'printf "AUXILIARY SHELL READY\n"; while IFS= read -r line; do printf "SHELL:%s\n" "$line"; done'], { cols, rows, name: 'xterm-256color' });
  });
  const createClaude = () => new ClaudeAdapter(async (agent, command) => {
    if (agent.target === 'unreachable') throw new Error('SSH connection refused (test)');
    if (agent.initScript) expect(command).toContain('eval ');
    if (command.includes('--help')) return '--session-id --resume\nPython 3.12';
    if (command.endsWith('pwd -P')) return '/srv/project\n';
    const options = JSON.parse(command.slice(command.indexOf("python3 - '") + "python3 - '".length, command.lastIndexOf("'")));
    const all = [...records.values()];
    const matching = options.sessionId ? all.filter(item => item.id === options.sessionId) : options.sessionIds ? all.filter(item => options.sessionIds.includes(item.id)) : all;
    return '__AGENT_HUB_JSON__' + JSON.stringify({ items: matching.slice(options.offset, options.offset + options.limit), total: matching.length, warnings: [] });
  });
  let sessions = createSessions();
  let auxiliaryShells = createAuxiliaryShells();
  const discoverRun = async (agent: { target: string }, command: string) => {
    if (agent.target === 'scan-host') return '__AGENT_HUB_HOST__ scanbox\n__AGENT_HUB_PYTHON__\n__AGENT_HUB_FOUND__ claude-code /usr/bin/claude\n';
    if (command.includes('__AGENT_HUB_GIT_STATUS__')) return '__AGENT_HUB_GIT_STATUS__1\n M web/src/App.tsx\0?? web/src/WorkspaceTools.tsx\0';
    if (command.includes('__AGENT_HUB_GIT_DIFF__')) return '__AGENT_HUB_GIT_DIFF__\ndiff --git a/web/src/App.tsx b/web/src/App.tsx\n--- a/web/src/App.tsx\n+++ b/web/src/App.tsx\n@@ -1 +1 @@\n-old\n+new\n';
    if (!command.includes('command -v')) {
      const path = command.includes("'~/work'") ? '~/work' : '~';
      const entries = path === '~'
        ? [{ name: 'work', path: '~/work', hasChildren: true }, { name: '.config', path: '~/.config', hasChildren: false }]
        : [{ name: 'src', path: '~/work/src', hasChildren: true }, { name: 'docs', path: '~/work/docs', hasChildren: false }];
      return '__AGENT_HUB_DIRS__' + JSON.stringify({ path, entries, truncated: false });
    }
    throw new Error('SSH connection refused (test)');
  };
  let app = await createApp({ store, sessions, auxiliaryShells, registry: new AgentRegistry([createClaude()], discoverRun), runCommand: discoverRun, dev: true });
  let origin = await app.listen(0);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const openPicker = async () => { await page.getByRole('button', { name: '添加对话', exact: true }).click(); await expect(page.getByRole('dialog', { name: '打开对话' })).toBeVisible(); };
  const chooseAgent = async (name: string) => { await page.getByRole('dialog', { name: '打开对话' }).getByRole('combobox', { name: '选择 Agent' }).click(); await page.getByRole('option', { name, exact: true }).click(); };
  const chooseLauncherAgent = async (name: string) => { await page.getByRole('region', { name: '打开对话' }).getByRole('combobox', { name: '选择 Agent' }).click(); await page.getByRole('option', { name, exact: true }).click(); };
  const activeTab = () => page.getByRole('tab', { selected: true });
  const activeTerminal = () => page.locator('.terminal-panel:not([hidden])');
  try {
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.locator('.sidebar, .statusbar, .list-footer')).toHaveCount(0);
    await expect(page.getByRole('img', { name: 'Agent Hub' })).toBeVisible();
    await expect(page.locator('.brand-dark')).toBeVisible();
    await expect(page.getByRole('radio', { name: '深色' })).toHaveAttribute('aria-checked', 'true');
    await page.getByRole('radio', { name: '浅色' }).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'modernLight');
    await expect(page.locator('.brand-light')).toBeVisible();
    await page.reload();
    await expect(page.getByRole('radio', { name: '浅色' })).toHaveAttribute('aria-checked', 'true');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'modernLight');
    await page.screenshot({ path: testInfo.outputPath('theme-light.png'), fullPage: true });
    await page.getByRole('radio', { name: '深色' }).click();
    await page.getByRole('button', { name: '注册第一个 Agent' }).click();
    await page.getByLabel('SSH 目标', { exact: true }).fill('scan-host');
    await page.getByRole('button', { name: '扫描环境', exact: true }).click();
    await expect(page.getByText('scanbox Claude')).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('discover.png'), fullPage: true });
    await page.getByRole('radio', { name: '手动配置' }).click();
    await page.getByLabel('名称', { exact: true }).fill('Dev Claude');
    await page.getByLabel('SSH 目标', { exact: true }).fill('dev-host');
    await page.getByLabel('默认工作目录', { exact: true }).fill('/srv/project');
    await page.getByText('高级配置', { exact: true }).click();
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill(initScript);
    await page.getByRole('button', { name: '测试连接', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('检查通过');
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.getByRole('region', { name: '打开对话' }).locator('.claude-icon').first()).toBeVisible();
    await expect(page.getByRole('region', { name: '打开对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '新建对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '打开历史对话' })).toBeVisible();
    await expect(page.getByLabel('最近工作目录')).toBeVisible();
    await expect(page.getByRole('tree', { name: 'dev-host目录' })).toHaveCount(0);
    await page.getByRole('textbox', { name: '工作目录', exact: true }).fill('~/work');
    await expect(page.getByRole('treeitem', { name: 'src' })).toBeVisible();
    await expect(page.getByRole('treeitem', { name: 'docs' })).toBeVisible();
    await page.getByRole('textbox', { name: '工作目录', exact: true }).fill('~/work/sr');
    await expect(page.getByRole('treeitem', { name: '~/work/src' })).toBeVisible();
    await expect(page.getByRole('treeitem', { name: '~/work/docs' })).toHaveCount(0);
    await expect(page.getByRole('tab')).toHaveCount(0);
    await page.screenshot({ path: testInfo.outputPath('empty.png'), fullPage: true });
    await expect(page.locator('.tab-actions button')).toHaveCount(0);
    await page.locator('.new-conversation form button.primary').click();
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    await expect(page.locator('.tab-actions button')).toHaveCount(1);
    await expect(page.getByRole('button', { name: '添加对话' })).toHaveText('+');
    await page.getByRole('radio', { name: '浅色' }).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'modernLight');
    await expect(page.locator('.xterm-viewport')).toHaveCSS('background-color', 'rgb(247, 247, 248)');
    await page.getByRole('radio', { name: '深色' }).click();
    await expect(activeTab()).toContainText('修复终端刷新问题');
    const firstSession = sessions.list()[0];
    const agentId = store.get().agents[0].id;
    await page.getByRole('button', { name: '辅助终端' }).click();
    const shellDrawer = page.getByRole('complementary', { name: '辅助终端' });
    await expect(shellDrawer.locator('.terminal-panel')).toHaveAttribute('data-state', 'connected');
    expect(shellSpawns).toBe(1);
    const drawerBox = await shellDrawer.boundingBox();
    expect(drawerBox && drawerBox.width / page.viewportSize()!.width).toBeGreaterThan(0.7);
    await shellDrawer.locator('.xterm-helper-textarea').fill('pwd');
    await shellDrawer.locator('.xterm-helper-textarea').press('Enter');
    await expect(shellDrawer.locator('.xterm-screen')).toContainText('SHELL:pwd');
    const closeBox = await shellDrawer.getByRole('button', { name: '收起工具抽屉' }).boundingBox();
    const headerBox = await shellDrawer.locator('.tool-header').boundingBox();
    expect(closeBox && headerBox && closeBox.x < headerBox.x + headerBox.width / 2).toBe(true);
    await page.keyboard.press('Control+Shift+KeyG');
    const reviewDrawer = page.getByRole('complementary', { name: '代码审查' });
    await expect(reviewDrawer.getByRole('heading', { name: '未暂存' })).toBeVisible();
    await expect(reviewDrawer.getByRole('heading', { name: '未跟踪' })).toBeVisible();
    await expect(reviewDrawer.getByRole('button', { name: 'M web/src/App.tsx' })).toBeVisible();
    await expect(reviewDrawer.locator('.diff-add')).toContainText('+new');
    await reviewDrawer.getByRole('radio', { name: '树形' }).click();
    await expect(reviewDrawer.getByRole('treeitem', { name: 'web' }).first()).toHaveAttribute('aria-expanded', 'true');
    await page.screenshot({ path: testInfo.outputPath('workspace-tools-tree.png'), fullPage: true });
    await reviewDrawer.getByRole('treeitem', { name: 'web' }).first().locator(':scope > button').click();
    await expect(reviewDrawer.getByRole('treeitem', { name: 'web' }).first()).toHaveAttribute('aria-expanded', 'false');
    await reviewDrawer.getByRole('radio', { name: '平铺' }).click();
    await expect(reviewDrawer.getByRole('button', { name: 'M web/src/App.tsx' })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('workspace-tools.png'), fullPage: true });
    await page.keyboard.press('Control+Shift+KeyG');
    await expect(page.locator('.tool-drawer')).toHaveCount(0);
    const shellToolButton = page.getByRole('button', { name: '辅助终端' });
    await shellToolButton.hover();
    await expect(shellToolButton).toHaveCSS('width', '40px');
    await expect(shellToolButton).toHaveCSS('transform', 'matrix(1, 0, 0, 1, -2, 0)');
    await page.screenshot({ path: testInfo.outputPath('workspace-tool-hover.png'), fullPage: true });
    await page.keyboard.press('Control+Shift+KeyT');
    await expect(page.getByRole('complementary', { name: '辅助终端' })).toBeVisible();
    expect(shellSpawns).toBe(1);
    await page.keyboard.press('Control+Shift+KeyT');
    await expect(page.getByLabel('辅助终端')).toHaveAttribute('aria-pressed', 'false');
    await page.locator('.xterm-helper-textarea').fill('browser-input');
    await page.locator('.xterm-helper-textarea').press('Enter');
    await openPicker();
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    expect(commands.at(-1)).toContain(`--resume '${historyId}'`);
    await expect(page.getByRole('tab')).toHaveCount(2);
    await openPicker();
    await expect(page.getByRole('heading', { name: '新建对话', exact: true })).toBeVisible();
    await page.screenshot({ path: testInfo.outputPath('add-conversation.png'), fullPage: true });
    await page.getByLabel('搜索对话').fill('existing-project');
    await expect(page.locator('.conversation')).toHaveCount(1);
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(page.getByRole('tab')).toHaveCount(2);
    expect(spawns).toBe(2);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await page.locator('.terminal-panel:not([hidden]) .xterm-helper-textarea').fill('scrollback');
    await page.locator('.terminal-panel:not([hidden]) .xterm-helper-textarea').press('Enter');
    await expect(page.locator('.terminal-panel:not([hidden]) .xterm-screen')).toContainText('SCROLLBACK:200');
    const bottom = await page.locator('.terminal-panel:not([hidden]) .xterm-viewport').evaluate(element => ({ top: element.scrollTop, max: element.scrollHeight - element.clientHeight }));
    expect(bottom.top).toBeGreaterThan(0);
    expect(Math.abs(bottom.max - bottom.top)).toBeLessThan(2);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).press('ArrowRight');
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(page.locator('.tool-drawer')).toHaveCount(0);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    const restoredBottom = await page.locator('.terminal-panel:not([hidden]) .xterm-viewport').evaluate(element => ({ top: element.scrollTop, max: element.scrollHeight - element.clientHeight }));
    expect(Math.abs(restoredBottom.max - restoredBottom.top)).toBeLessThan(2);
    await page.getByRole('tab', { name: /接入之前已有的对话/ }).click();
    await page.reload();
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    expect(spawns).toBe(2);
    await page.screenshot({ path: testInfo.outputPath('tabs.png'), fullPage: true });

    await page.getByRole('button', { name: '管理 Agents' }).click();
    await expect(page.locator('.managed-agent .claude-icon').first()).toBeVisible();
    await expect(page.getByRole('group', { name: 'SSH · dev-host' })).toBeVisible();
    await page.getByRole('button', { name: '注册 Agent', exact: true }).click();
    await page.getByRole('radio', { name: '手动配置' }).click();
    await page.getByLabel('名称', { exact: true }).fill('Second Claude');
    await page.getByLabel('SSH 目标', { exact: true }).fill('dev-host');
    await page.getByText('高级配置', { exact: true }).click();
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill(initScript);
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeDisabled();
    await page.getByRole('button', { name: '测试连接', exact: true }).click();
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeEnabled();
    await page.getByRole('button', { name: '保存 Agent' }).click();
    // The top-level agent selector is gone: tabs from every agent stay visible together.
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(page.getByRole('group', { name: 'Dev Claude', exact: true })).toBeVisible();
    await openPicker();
    await page.getByRole('combobox', { name: '选择 Agent' }).click();
    await expect(page.getByRole('group', { name: 'SSH · dev-host' })).toBeVisible();
    await expect(page.getByRole('option', { name: 'Dev Claude' }).locator('.claude-icon')).toBeVisible();
    await expect(page.getByRole('option', { name: 'Second Claude' }).locator('.claude-icon')).toBeVisible();
    await page.getByRole('option', { name: 'Second Claude', exact: true }).click();
    await page.getByRole('dialog', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    // Same conversation under a different agent opens a new tab in that agent's group.
    await expect(page.getByRole('tab')).toHaveCount(3);
    await expect(activeTab()).toContainText('接入之前已有的对话');
    await expect(page.getByRole('group', { name: 'Second Claude', exact: true })).toBeVisible();
    const deletes: string[] = [];
    page.on('request', request => { if (request.method() === 'DELETE' && new URL(request.url()).pathname.startsWith('/api/sessions/')) deletes.push(request.url()); });
    await page.getByRole('button', { name: '关闭 修复终端刷新问题' }).click();
    await expect(page.getByRole('tab')).toHaveCount(2);
    expect(sessions.get(firstSession.id)?.info.status).toBe('running');
    await page.reload();
    await expect(page.getByRole('tab')).toHaveCount(2);
    await openPicker();
    await chooseAgent('Dev Claude');
    await page.getByRole('button', { name: /修复终端刷新问题.*活跃/ }).click();
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    expect(spawns).toBe(2);
    await expect.poll(() => store.get().workspace.tabs.filter(tab => tab.agentId === agentId).map(tab => tab.agentSessionId)).toEqual([historyId, firstSession.agentSessionId]);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await activeTerminal().locator('.xterm-viewport').evaluate(element => { element.scrollTop = 0; element.dispatchEvent(new Event('scroll')); });
    await expect(activeTerminal().locator('.xterm-screen')).toContainText('REPLY:browser-input');
    expect(deletes).toEqual([]);

    const savedWorkspace = store.get().workspace;
    await page.close();
    const freshContext = await browser.newContext();
    page = await freshContext.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.getByRole('tab')).toHaveCount(3);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    expect(store.get().workspace).toEqual(savedWorkspace);
    expect(spawns).toBe(2);
    await page.setViewportSize({ width: 390, height: 720 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await expect(page.getByRole('button', { name: '添加对话', exact: true })).toBeInViewport();
    await page.getByRole('tab').last().evaluate((element: HTMLElement) => element.click());
    await expect(page.getByRole('tab').last()).toHaveAttribute('aria-selected', 'true');
    const activeTabBox = await activeTab().boundingBox(), tabbarBox = await page.locator('.tabs').boundingBox();
    expect(activeTabBox && tabbarBox && activeTabBox.x >= tabbarBox.x && activeTabBox.x + activeTabBox.width <= tabbarBox.x + tabbarBox.width).toBe(true);
    await page.screenshot({ path: testInfo.outputPath('narrow.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 980 });
    await openPicker();
    await chooseAgent('Dev Claude');
    await page.getByRole('button', { name: /即将删除的对话/ }).click();
    await expect(activeTab()).toContainText('即将删除的对话');
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await page.close();
    await app.close();
    records.delete(missingId);
    store = await new ConfigStore(directory).load();
    sessions = createSessions();
    auxiliaryShells = createAuxiliaryShells();
    app = await createApp({ store, sessions, auxiliaryShells, registry: new AgentRegistry([createClaude()], discoverRun), runCommand: discoverRun, dev: true });
    origin = await app.listen(0);
    const beforeResume = spawns;
    page = await freshContext.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${origin}/#token=${app.token}`);
    await expect(page.getByRole('tab')).toHaveCount(4);
    await expect(activeTab()).toContainText('修复终端刷新问题');
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    expect(sessions.list()).toHaveLength(1);
    expect(spawns).toBe(beforeResume + 1);
    expect(commands.at(-1)).toContain(`--resume '${firstSession.agentSessionId}'`);
    await page.screenshot({ path: testInfo.outputPath('restore.png'), fullPage: true });
    // The tab whose history was deleted server-side lost its title and cannot resume.
    await page.getByRole('tab', { name: /新对话/ }).click();
    await expect(page.getByRole('alert')).toContainText('Agent 历史已删除');
    expect(spawns).toBe(beforeResume + 1);
    await page.getByRole('tab', { name: /修复终端刷新问题/ }).click();
    await expect(activeTerminal()).toHaveAttribute('data-state', 'connected');
    expect(spawns).toBe(beforeResume + 1);
    await expect(page.getByRole('tab')).toHaveCount(4);
    await page.locator('.xterm-helper-textarea').fill('exit');
    await page.locator('.xterm-helper-textarea').press('Enter');
    await expect(page.locator('.terminal-status')).toContainText('进程已退出');
    await expect(activeTab()).toContainText('已退出');
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    for (let count = 4; count > 0; count--) { await page.locator('.tab-close').last().click(); await expect(page.getByRole('tab')).toHaveCount(count - 1); }
    await expect(page.getByRole('region', { name: '打开对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '新建对话' })).toBeVisible();
    await expect(page.getByRole('heading', { name: '打开历史对话' })).toBeVisible();
    await page.reload();
    await expect(page.getByRole('tab')).toHaveCount(0);
    await chooseLauncherAgent('Second Claude');
    await page.getByRole('region', { name: '打开对话' }).getByRole('button', { name: /接入之前已有的对话/ }).click();
    await expect(page.getByRole('tab')).toHaveCount(1);
    await page.getByRole('button', { name: '管理 Agents' }).click();
    await page.getByRole('button', { name: '编辑 Second Claude' }).click();
    await page.getByText('高级配置', { exact: true }).click();
    await expect(page.getByLabel('初始化脚本（Bash）', { exact: true })).toHaveValue(initScript);
    await page.getByLabel('初始化脚本（Bash）', { exact: true }).fill('export MAM_TEST_ENV=changed');
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeDisabled();
    await page.getByRole('button', { name: '测试连接', exact: true }).click();
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeEnabled();
    await page.screenshot({ path: testInfo.outputPath('init-script.png'), fullPage: true });
    await page.getByRole('button', { name: '保存 Agent' }).click();
    await expect(page.getByText('Agent 环境已更改，无法在当前环境恢复此 tab。')).toBeVisible();
    await page.getByRole('button', { name: '管理 Agents' }).click();
    await page.getByRole('button', { name: '编辑 Second Claude' }).click();
    await page.getByLabel('SSH 目标', { exact: true }).fill('unreachable');
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeDisabled();
    await page.getByRole('button', { name: '测试连接', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('connection refused');
    await expect(page.getByRole('button', { name: '保存 Agent' })).toBeDisabled();
    await page.getByRole('button', { name: '关闭', exact: true }).click();
    await expect(page.getByText('Agent 环境已更改，无法在当前环境恢复此 tab。')).toBeVisible();
    await expect(page.getByRole('button', { name: '恢复对话' })).toHaveCount(0);
    await openPicker();
    await page.getByLabel('搜索对话').fill('no results');
    await expect(page.getByText('没有匹配的对话')).toBeVisible();
    const saved = await readFile(join(directory, 'config.json'), 'utf8');
    expect(saved).not.toContain('browser-input');
    expect(saved).not.toContain('修复终端刷新问题');
    expect(saved).not.toContain('接入之前已有的对话');
    expect(saved).toContain(historyId);
    expect(errors.filter(message => message !== 'WebSocket closed without opened.')).toEqual([]);
    await freshContext.close();
  } finally { await app.close(); await rm(directory, { recursive: true, force: true }); }
});
